app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/easypatientdb
    username: postgres
    password: password
    pool-size: 30
#    jdbc-url: jdbc:postgresql://139.162.138.193:5432/easypatient
#    username: easypatient
#    password: easypatient123
#    pool-size: 30
