version: '3.3'

services:
  web:
    build: .
    ports:
      - 8085:8085
    depends_on:
      - localhost
  localhost:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=easyPatient
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=easypatientdb
